### ISSUE TITLE
SSH error

### ISSUE THREAD

**Issue by kephas** [mkroli/codebrag-docker#1]
Despite the ssh config file (maybe because it's JGit and not Git?), I get the following error with an SSH remote:

`org.eclipse.jgit.api.errors.TransportException: git@{HOST}:{REPO}: UnknownHostKey: {HOST}. RSA key fingerprint is XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX`

**Comment by mkroli** [comment]
It works for me. Can you give me some information how to reproduce it?
